﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using Microsoft.ML;

namespace AutoMLDotNet
{
    public partial class MLModel1
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"Data", @"Data"),new InputOutputColumnPair(@"TimeSunRise", @"TimeSunRise"),new InputOutputColumnPair(@"TimeSunSet", @"TimeSunSet")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"UNIXTime", @"UNIXTime"),new InputOutputColumnPair(@"Temperature", @"Temperature"),new InputOutputColumnPair(@"Pressure", @"Pressure"),new InputOutputColumnPair(@"Humidity", @"Humidity"),new InputOutputColumnPair(@"WindDirection(Degrees)", @"WindDirection(Degrees)"),new InputOutputColumnPair(@"Speed", @"Speed")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Time",outputColumnName:@"Time"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Data",@"TimeSunRise",@"TimeSunSet",@"UNIXTime",@"Temperature",@"Pressure",@"Humidity",@"WindDirection(Degrees)",@"Speed",@"Time"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"Radiation",inputColumnName:@"Radiation"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.SdcaMaximumEntropy(new SdcaMaximumEntropyMulticlassTrainer.Options(){L1Regularization=1F,L2Regularization=0.1F,LabelColumnName=@"Radiation",FeatureColumnName=@"Features"}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
}
